otree_project/lemon_market/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random


doc = """
In a lemon market of
<a href="http://people.bu.edu/ellisrp/EC387/Papers/1970Akerlof_Lemons_QJE.pdf" target="_blank">
    Akerlof (1970)
</a>, 2 buyers and 1 seller interact for 3 periods. The implementation is
based on
<a href="http://people.virginia.edu/~cah2k/lemontr.pdf" target="_blank">
    Holt (1999)
</a>.
"""


class Constants(BaseConstants):
    name_in_url = 'lemon_market'
    players_per_group = 3
    num_rounds = 3

    instructions_template = 'lemon_market/Instructions.html'

    initial_endowment = c(50)


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    sale_price = models.CurrencyField()

    seller_id = models.PositiveIntegerField(
        choices=[(i, 'Buy from seller %i' % i) for i in
                 range(1, Constants.players_per_group)] + [
                    (0, 'Buy nothing')],
        widget=widgets.RadioSelect(),
        doc="""0 means no purchase made"""
    )  # seller index

    def set_payoff(self):
        for p in self.get_players():
            p.payoff = Constants.initial_endowment

        if self.seller_id is not 0:
            seller = self.get_seller()
            self.sale_price = seller.seller_proposed_price

            buyer = self.get_player_by_role('buyer')
            buyer.payoff += seller.seller_proposed_quality + 5 - seller.seller_proposed_price
            seller.payoff += seller.seller_proposed_price - seller.seller_proposed_quality

    def get_seller(self):
        for p in self.get_players():
            if 'seller' in p.role() and p.seller_id() == self.seller_id:
                return p


class Player(BasePlayer):
    # seller
    seller_proposed_price = models.CurrencyField(
        min=0, max=Constants.initial_endowment,
        verbose_name='Please indicate a price (from 0 to %i) you want to sell'
                     % Constants.initial_endowment)

    seller_proposed_quality = models.CurrencyField(
        choices=[
            (30, 'High'),
            (20, 'Medium'),
            (10, 'Low')],
        verbose_name='Please select a quality grade you want to produce',
        widget=widgets.RadioSelectHorizontal())

    def seller_id(self):
        # player 1 is the buyer, so seller 1 is actually player 2
        return (self.id_in_group - 1)

    def role(self):
        if self.id_in_group == 1:
            return 'buyer'
        return 'seller {}'.format(self.seller_id())

otree_project/lemon_market/_builtin/__init__.py
# This file is auto-generated. Don't change anything in this file.
from .. import models
import otree.api

class Page(otree.api.Page):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):


    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

otree_project/lemon_market/views.py
from . import models
from ._builtin import Page, WaitPage
from .models import Constants
from otree.common import safe_json


class Introduction(Page):
    def is_displayed(self):
        return self.subsession.round_number == 1


class Production(Page):
    def is_displayed(self):
        return self.player.role().startswith('seller')

    form_model = models.Player
    form_fields = ['seller_proposed_price', 'seller_proposed_quality']


class SimpleWaitPage(WaitPage):
    pass


class Purchase(Page):
    def is_displayed(self):
        return self.player.role() == 'buyer'

    form_model = models.Group
    form_fields = ['seller_id']


class ResultsWaitPage(WaitPage):
    def after_all_players_arrive(self):
        self.group.set_payoff()


class Results(Page):
    def vars_for_template(self):
        return {'seller': self.group.get_seller()}


class FinalResults(Page):
    def is_displayed(self):
        return self.subsession.round_number == Constants.num_rounds

    def vars_for_template(self):
        # Filling the data for HighCharts graph

        series = []

        transaction_prices = [g.sale_price for g in self.group.in_all_rounds()]
        series.append({
            'name': 'Transaction Price',
            'data': transaction_prices})

        for player in self.group.get_players():
            payoffs = [p.payoff for p in player.in_all_rounds()]
            series.append(
                {'name': 'Earnings for %s' % player.role().capitalize(),
                 'data': payoffs})
        highcharts_series = safe_json(series)

        round_numbers = safe_json(list(range(1, Constants.num_rounds + 1)))

        return {
            'highcharts_series': highcharts_series,
            'round_numbers': round_numbers
        }


page_sequence = [
    Introduction,
    Production,
    SimpleWaitPage,
    Purchase,
    ResultsWaitPage,
    Results,
    FinalResults,
]

otree_project/lemon_market/templates/lemon_market/FinalResults.html
{% extends "global/Base.html" %}
{% load otree_tags %}

{% block title %}Results for all rounds{% endblock title %}

{% block content %}
    <p>
        You have finished all {{ Constants.num_rounds }} periods. Purchases for
        all periods are
        summarized below:
    </p>
    <div id="highcharts-container"
         style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    <p>
        You are <strong>{{ player.role }}</strong>.
    </p>

    {% next_button %}

{% endblock %}

{% block scripts %}
    <script src="//code.highcharts.com/highcharts.js"></script>
    <script src="//code.highcharts.com/highcharts-3d.js"></script>

    <script>
        $(function () {
            $('#highcharts-container').highcharts({
                title: {
                    text: 'Results'
                },
                xAxis: {
                    categories: {{ round_numbers }},
                    title: {text: 'Round'}
                },
                yAxis: {
                    title: {
                        text: 'Points'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    valueSuffix: 'points'
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle',
                    borderWidth: 0
                },
                series: {{ highcharts_series }}
            });
        });
    </script>
{% endblock %}

otree_project/lemon_market/templates/lemon_market/Instructions.html
{% load otree_tags staticfiles %}

<div class="instructions well well-lg">

    <h3 class="panel-sub-heading">
        Instructions
    </h3>

    <p>
        In this study, you will be grouped randomly and anonymously with
        another 2 participants. One of you will be randomly assigned to be the
        buyer and the other 2 the sellers. Sellers and the buyer can trade for
        {{ Constants.num_rounds }} periods. Prior to making any decision, you will learn your role,
        which will remain unchanged for all periods.
    </p>
    <p>
        At the beginning of each period, each of you will receive 50 points.
        The sellers will begin by privately choosing a <strong>price</strong>
        (from 0 to 50) and a <strong>quality grade</strong> for their products.
        Then the buyer will have the chance to purchase from one of the sellers
        at the price listed. Before purchase, the buyer will not observe
        grades. After purchase, the price and grade of the bought unit will be
        revealed to all. The grade can be <strong>high, medium, or
        low;</strong> higher grade costs more to produce and is worth more to
        the buyer. The table below shows production costs to the sellers and
        values to the buyer of different grades (in points):
    </p>
    <table class=table>
        <thead>
        <tr>
            <th>Grade</th>
            <th>High</th>
            <th>Medium</th>
            <th>Low</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>Production Cost to Sellers</th>
            <td>30</td>
            <td>20</td>
            <td>10</td>
        </tr>
        <tr>
            <th>Value to the Buyer</th>
            <td>35</td>
            <td>25</td>
            <td>15</td>
        </tr>
        </tbody>
    </table>
    <p>
        The buyer can buy up to 1 unit of the commodity during a period and
        each seller can produce up to 1 unit in a period. <strong>Unsold units
        are not produced and hence incur no cost.</strong>
    </p>
    <p>
        The period payoff for the buyer is:<br/>
        <strong>
            Buyer's period payoff = 50 + value of the grade purchased -
            seller's price
        </strong></p>
    <p>
        The period payoff the sellers is:<br/>
        <strong>
            Seller's period payoff = 50 + seller's price - cost of the grade
            produced
        </strong></p>
</div>

otree_project/lemon_market/templates/lemon_market/Introduction.html
{% extends "global/Base.html" %}
{% load otree_tags %}

{% block title %}Introduction{% endblock %}

{% block content %}
{% include Constants.instructions_template %}
{% next_button %}
{% endblock %}

otree_project/lemon_market/templates/lemon_market/Production.html
{% extends "global/Base.html" %}
{% load otree_tags %}

{% block title %}
    Production (Period {{ subsession.round_number }} of {{ Constants.num_rounds }})
{% endblock %}

{% block content %}

    <p>You are {{ player.role }}</p>

    {% formfield player.seller_proposed_quality %}
    {% formfield player.seller_proposed_price %}

    {% next_button %}
    {% include Constants.instructions_template %}

{% endblock %}

otree_project/lemon_market/templates/lemon_market/Purchase.html
{% extends "global/Base.html" %}
{% load otree_tags %}

{% block title %}
    Purchase (Period {{ subsession.round_number }} of {{ Constants.num_rounds }})
{% endblock %}

{% block content %}
<p>You are buyer.</p>
<p>
    <strong>Below are the listed prices from the sellers:</strong><br/>
    {% for p in group.get_players %}
    {% if 'seller' in p.role %}
    <i>Price from {{p.role}}: {{p.seller_proposed_price}}</i><br/>
    {% endif %}
    {% endfor %}
</p>

{% formfield group.seller_id with label="Please make a purchase decision:" %}

{% next_button %}

{% include Constants.instructions_template %}

{% endblock %}

otree_project/lemon_market/templates/lemon_market/Results.html
{% extends "global/Base.html" %}
{% load otree_tags %}

{% block title %}
    Results (Period {{ subsession.round_number }} of {{ Constants.num_rounds }}
    )
{% endblock %}


{% block content %}
    You are {{ player.role }}.
    {% if group.seller_id %}
        {% if player.role == 'buyer' %}
            You bought from seller {{ group.seller_id }}
            at a price of <strong>{{ group.sale_price }}</strong>.
            The quality grade of your purchase is <strong>{{ seller.get_seller_proposed_quality_display }}</strong>.
        {% else %}
            The buyer purchased a <strong>{{ seller.get_seller_proposed_display }}</strong> grade
            from <strong>{% if player == seller %}you{% else %}{{ seller.role }}{% endif %}</strong>
            at a price of <strong>{{ group.sale_price }}</strong>.
        {% endif %}
        {# buyer bought nothing #}
    {% elif player.role == 'buyer' %}
        You bought nothing in this period.
    {% else %}
        The buyer bought nothing in this period.
    {% endif %}
    Thus your period payoff is <strong>{{ player.payoff }}</strong>.

    <p> {% next_button %}</p>
    {% include Constants.instructions_template %}
{% endblock %}